Repository hyperledger/firefly, pull requests merged in 2022-01, with the labels that each got.

#422 Fix token account listing on Postgres
  docs/swagger/swagger.yaml
  internal/apiserver/route_get_token_account_pools.go
  internal/apiserver/route_get_token_accounts.go
  internal/database/sqlcommon/tokenbalance_sql.go
  pkg/database/plugin.go
  test/e2e/restclient.go
  test/e2e/tokens_test.go
Labels: backport-candidate

#429 Fix querying transfers by tx or type, batches by tx
  docs/swagger/swagger.yaml
  internal/database/sqlcommon/batch_sql.go
  internal/database/sqlcommon/tokentransfer_sql.go
  pkg/database/plugin.go
Labels: backport_v0.11.x

#435 Fail transaction when token transfer operation fails
  internal/events/operation_update.go
  internal/events/operation_update_test.go
Labels: backport-candidate

#438 Ready state changes require a bump to the message to re-sequence it
  internal/database/sqlcommon/message_sql.go
  internal/database/sqlcommon/message_sql_test.go
  internal/events/tokens_transferred.go
  internal/events/tokens_transferred_test.go
  mocks/databasemocks/plugin.go
  pkg/database/plugin.go
Labels: backport-candidate, backport-complete

#439 v0.11.x backport: Ready state changes require a bump to the message to re-sequence it
  internal/database/sqlcommon/message_sql.go
  internal/database/sqlcommon/message_sql_test.go
  internal/events/tokens_transferred.go
  internal/events/tokens_transferred_test.go
  mocks/databasemocks/plugin.go
  pkg/database/plugin.go
Labels: backport_v0.11.x
